name: market_price
description: "Market Price"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  dartx: ^1.2.0
  easy_localization: ^3.0.8
  pretty_dio_logger:
  pull_to_refresh: ^2.0.0
  provider: ^6.1.5+1
  image_picker: ^1.2.0
  lottie: ^3.3.2
  carousel_slider: ^5.1.1
  photo_view: ^0.15.0
  line_icons:
  cached_network_image: 3.4.1
  google_fonts: ^6.3.2
  shimmer: 3.0.0
  flex_color_scheme:
  lucide_icons: ^0.257.0
  fl_chart: 1.1.1
  syncfusion_flutter_charts: ^31.2.15

#  smooth_page_indicator: ^1.2.1
#  flutter_spinkit: ^5.2.2
#  url_launcher:
#  wolt_modal_sheet: ^0.11.0
#  flutter_zoom_drawer: ^3.2.0
#  dotted_line: 3.2.3
  toastification: ^3.0.3

#  firebase_messaging: ^16.0.3
#  flutter_local_notifications: ^19.5.0
#  firebase_core: ^4.2.0
  flutter_launcher_icons: ^0.14.4
#  qr_flutter: 4.1.0
  system_info_agent: ^1.0.1
#  qr_breeze: ^0.0.4
#  svg_flutter:
#  animate_do: ^4.2.0
#  open_filex:

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/fuel_logo_rv.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true
  assets:
    - languages/en-US.json
    - languages/my-MM.json
    - assets/images/
    - assets/icons/
    - assets/anim/


